### 5,10, 15 agentes

- Age [25,60]
- Qualifications [0,4] "nurse;cpr;physio;doctor"
- Location ????
- Religion A,B,C
- Gender M/F
- Languages [1,3] spanish, catalan, english
- Race white, latin-american, black or asian
- Availabilities "15;39"

### 5, 8, 10 servicios

- Age [70,90]
- Type [0,4] "nurse;cpr;physio;doctor"
- Location ?????
- Religion A,B,C
- Gender M/F
- Languages [1,3] spanish, catalan, english
- Race white, latin-american, black or asian
- TimeSlot dos numeros entre 15 i 39

In [ ]:
import pandas as pd
import numpy as np
from random import randrange,sample,randint,shuffle
from geopy.distance import distance
#Configuracions de (A,U,S=U*(4 o 5)): (12,30),(15,30),(20,30). 20 instancies per setting, timeout=1h
#Resultats: #resoltes (va be tenir unsats per veure), valor dels 3 components de la funcio objectiu
#Encoding estratificat per les UNSAT, opcionalment es poden fer els serveis

#ARGS: U, A, V tal que S=U*V
#QUE faci un print enlloc de write a instancia.txt
U = 30 #Nombre d'usuaris
A = 12 #Nombre d'agents
S = U*V #Nombre de serveis {}
TS = 12*5 #Nombre de time slots
dist = [2.5,5,15,25,35,45,60,70,80,90,95,100]

gender_labels = ['M','F']
religion_labels = ['A','B','C']
languages_labels = ["spanish", "catalan", "english"]
type_labels = ["","nurse", "cpr", "physio", "doctor"]
race_labels = ["white", "latin-american", "black", "asian"]

lat =[
"41.3815752781548","41.3559120196836","41.3482745236520","41.4629832100058",
"41.4205718274176","41.4200823434142","41.4410422907494","41.4131703459941",
"41.3680119940713","41.2902486755464","41.2965206008947","41.2980521776798",
"41.2986079051265","41.4255770243766","41.4092758094591", "41.3815752781548",
"41.3559120196836","41.3482745236520","41.4629832100058","41.4205718274176",
"41.4200823434142","41.4410422907494","41.4131703459941","41.3680119940713",
"41.2902486755464","41.2965206008947","41.2980521776798","41.2986079051265",
"41.4255770243766","41.4092758094591"]

long =[
"1.98513272094305","2.11713228334789","2.26488244348681","2.24786162179945",
"2.15257024090813","2.07977758336782","2.13520828449359","2.25664519810334",
"2.16001633375526","2.21418980601852","2.09379793713258","2.20410100139758",
"2.14110807067940","2.14907409962812","2.25351119355848","1.98513272094305",
"2.11713228334789","2.26488244348681","2.24786162179945","2.15257024090813",
"2.07977758336782","2.13520828449359","2.25664519810334","2.16001633375526",
"2.21418980601852","2.09379793713258","2.20410100139758","2.14110807067940",
"2.14907409962812","2.25351119355848" ]

In [ ]:
def create_random_labels(labels, min_labels, max_labels, num):
    rows = []
    for i in range(num):
        rows.append([x for x in sample(labels, randrange(min_labels,max_labels+1))])
    return rows

In [ ]:

df_agents = pd.DataFrame()

df_agents['Id'] = [x for x in range(A)]
df_agents['Age'] = [randint(25, 60) for x in range(A)]
df_agents['Qualifications'] = create_random_labels(type_labels, 0, 3, A)
df_agents['Location'] = [";".join(x) for x in zip(*[sample(lat,A), sample(long,A)])]
df_agents['Region'] = np.random.choice(religion_labels, A)
df_agents['Gender'] = np.random.choice(gender_labels, A)
df_agents['Languages'] = create_random_labels(languages_labels, 1, 2, A)
df_agents['Race'] = np.random.choice(race_labels, A)

TSA = []
for a in range(A):
    hours=randint(4, 12) #Que treballin!
    if randint(0,1):
        TSA.append(([1]*hours+[0]*(12-hours))*5)
    else:
        TSA.append(([0]*(12-hours)+[1]*hours)*5)

df_agents['TSA'] = TSA

df_agents

,Id,Age,Qualifications,Location,Region,Gender,Languages,Race,TSA
0,0,37,[],41.3680119940713;1.98513272094305,A,M,"[spanish, catalan]",black,"[0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, ..."
1,1,34,"[physio, ]",41.3559120196836;2.14110807067940,A,M,[spanish],black,"[1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, ..."
2,2,26,[physio],41.2986079051265;2.13520828449359,A,F,[spanish],latin-american,"[0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, ..."
3,3,55,[],41.4255770243766;2.21418980601852,A,M,"[english, catalan]",asian,"[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ..."
4,4,32,[],41.4092758094591;2.07977758336782,B,M,[catalan],asian,"[0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, ..."
5,5,42,"[, nurse, cpr]",41.3815752781548;2.09379793713258,A,F,[english],white,"[0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, ..."
6,6,33,"[nurse, physio]",41.4131703459941;2.15257024090813,C,F,"[spanish, catalan]",asian,"[1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, ..."
7,7,43,[],41.4255770243766;2.24786162179945,B,M,"[english, catalan]",white,"[0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, ..."
8,8,41,"[cpr, physio]",41.2902486755464;2.25664519810334,C,F,"[english, spanish]",black,"[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, ..."
9,9,52,"[nurse, ]",41.2986079051265;2.16001633375526,C,M,"[english, spanish]",white,"[1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, ..."
10,10,42,"[doctor, physio]",41.4092758094591;2.09379793713258,C,F,[catalan],white,"[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, ..."
11,11,60,"[doctor, , nurse]",41.4205718274176;2.07977758336782,A,M,"[catalan, spanish]",latin-american,"[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ..."
12,12,45,[],41.4200823434142;2.26488244348681,B,F,"[catalan, spanish]",asian,"[0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, ..."
13,13,38,[],41.3482745236520;2.15257024090813,A,M,[english],latin-american,"[1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, ..."
14,14,26,"[nurse, physio, doctor]",41.2980521776798;2.20410100139758,B,M,[catalan],latin-american,"[1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, ..."
15,15,57,"[nurse, physio]",41.2965206008947;2.14110807067940,C,M,"[catalan, spanish]",latin-american,"[0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, ..."
16,16,48,"[physio, nurse, ]",41.2902486755464;2.26488244348681,B,F,"[english, catalan]",white,"[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ..."
17,17,47,[nurse],41.3559120196836;2.11713228334789,B,F,"[english, catalan]",white,"[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ..."
18,18,30,[cpr],41.4629832100058;2.14907409962812,B,F,"[english, catalan]",white,"[0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, ..."
19,19,57,[cpr],41.2965206008947;2.16001633375526,A,F,[spanish],latin-american,"[0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, ..."

In [ ]:
#usuaris

df_usuaris = pd.DataFrame()

df_usuaris['Id'] = [x for x in range(U)]
df_usuaris['Age'] = [randint(70, 90) for x in range(U)]
df_usuaris['Location'] = [";".join(x) for x in zip(*[sample(lat,U), sample(long,U)])]
#df_usuaris['Region'] = np.random.choice(religion_labels, U)
df_usuaris['Gender'] = np.random.choice(gender_labels, U)
df_usuaris['Languages'] = np.random.choice(race_labels, U)#create_random_labels(languages_labels, 1, 1, U)
df_usuaris['Race'] = np.random.choice(race_labels, U)

df_usuaris

,Id,Age,Location,Gender,Languages,Race
0,0,77,41.4255770243766;2.25351119355848,F,latin-american,black
1,1,89,41.4205718274176;2.13520828449359,F,black,white
2,2,85,41.4255770243766;1.98513272094305,M,white,asian
3,3,88,41.4131703459941;2.25664519810334,M,latin-american,asian
4,4,72,41.3482745236520;2.16001633375526,F,white,white
5,5,73,41.3482745236520;2.16001633375526,F,asian,black
6,6,74,41.4200823434142;2.21418980601852,M,asian,asian
7,7,86,41.4092758094591;2.25351119355848,F,black,white
8,8,75,41.4410422907494;2.20410100139758,F,white,asian
9,9,82,41.4205718274176;2.14110807067940,M,asian,black
10,10,81,41.3559120196836;2.14907409962812,F,black,black
11,11,70,41.2902486755464;2.11713228334789,M,black,white
12,12,76,41.3680119940713;2.24786162179945,M,black,black
13,13,70,41.3680119940713;2.15257024090813,M,latin-american,latin-american
14,14,85,41.3815752781548;2.21418980601852,M,latin-american,latin-american
15,15,71,41.2965206008947;2.14110807067940,M,asian,white
16,16,85,41.2986079051265;2.11713228334789,M,asian,asian
17,17,75,41.4200823434142;2.07977758336782,M,latin-american,black
18,18,88,41.4131703459941;2.09379793713258,M,asian,asian
19,19,73,41.2980521776798;2.15257024090813,M,white,black
20,20,86,41.4092758094591;1.98513272094305,M,black,asian
21,21,77,41.4629832100058;2.07977758336782,M,latin-american,white
22,22,81,41.4629832100058;2.09379793713258,M,white,asian
23,23,87,41.2965206008947;2.26488244348681,F,white,latin-american
24,24,79,41.2902486755464;2.25664519810334,M,asian,black
25,25,88,41.2986079051265;2.20410100139758,M,latin-american,white
26,26,86,41.3559120196836;2.26488244348681,M,black,latin-american
27,27,75,41.2980521776798;2.14907409962812,M,asian,white
28,28,82,41.4410422907494;2.13520828449359,M,white,asian
29,29,78,41.3815752781548;2.24786162179945,M,white,white

In [ ]:
#services

def serviceTimeSlot(dist=dist):
    repetitions = 1
    duration = randint(1, 4)
    slot = randint(0,99)
    for i in range(len(dist)):
        if slot<dist[i]:
            day = [0]*i+[1]*duration+[0]*(len(dist)-duration-i)
            if len(day)>12:
                day = day[-12:]
            break
    service = [day]*repetitions+[[0]*12]*(5-repetitions)
    shuffle(service)
    return service

df_serveis = pd.DataFrame()

df_serveis['Id'] = [x for x in range(S)]
df_serveis['user'] = [sample(list(df_usuaris['Id']),1)[0] for x in range(S)]
df_serveis['Type'] = np.random.choice(type_labels, S)#create_random_labels(type_labels, 0, 1, S)
df_serveis['TimeSlot'] = [serviceTimeSlot() for x in range(S)]

df_serveis
#df.to_csv("services_" + str(num) + ".csv", sep = ";",index=False)

    Id  user    Type                                           TimeSlot
0    0    25   nurse  [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, ...
1    1    13          [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, ...
2    2    21          [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, ...
3    3    29     cpr  [[0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0], [0, 0, ...
4    4    25     cpr  [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, ...
5    5    27          [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, ...
6    6    18     cpr  [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, ...
7    7    21  doctor  [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, ...
8    8    15     cpr  [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, ...
9    9    12          [[0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0], [0, 0, ...
10  10    27   nurse  [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, ...
11  11    21  physio  [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, ...
12  12     2  physio  [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, ...
13  13    11  physio  [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, ...
14  14    16          [[0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1], [0, 0, ...
15  15    19          [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, ...
16  16    19  physio  [[0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0], [0, 0, ...
17  17    28  doctor  [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, ...
18  18    25     cpr  [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, ...
19  19    28  physio  [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, ...
20  20    13  physio  [[0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0], [0, 0, ...
21  21    22          [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, ...
22  22    21          [[0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0], [0, 0, ...
23  23     9  doctor  [[0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0], [0, 0, ...
24  24    19  physio  [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, ...
25  25     6     cpr  [[0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0], [0, 0, ...
26  26    27  physio  [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, ...
27  27    28     cpr  [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, ...
28  28     4     cpr  [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, ...
29  29    14          [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, ...
30  30    11   nurse  [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, ...
31  31     0          [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, ...
32  32    10  doctor  [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, ...
33  33    25  physio  [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, ...
34  34     2  physio  [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, ...
35  35    18          [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, ...
36  36     0   nurse  [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [1, 0, ...
37  37    26   nurse  [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, ...
38  38    23          [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, ...
39  39    10  physio  [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, ...
40  40    23  physio  [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, ...
41  41    23   nurse  [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, ...
42  42    16          [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, ...
43  43    24     cpr  [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, ...
44  44     7     cpr  [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, ...
45  45     8     cpr  [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, ...
46  46     2     cpr  [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, ...
47  47    14          [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, ...
48  48    20  doctor  [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, ...
49  49    24     cpr  [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, ...
50  50    28   nurse  [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, ...
51  51    27   nurse  [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, ...
52  52    25          [[0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0], [0, 0, ...
53  53    11   nurse  [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, ...
54  54    29  physio  [[0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0], [0, 0, ...
55  55    16   nurse  [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, ...
56  56    15  doctor  [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, ...
57  57     9     cpr  [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, ...
58  58     9   nurse  [[0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0], [0, 0, ...
59  59    28  doctor  [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, ...

In [ ]:
SU = df_serveis[['user','Id']].groupby(by=['user']).agg(list)['Id'].to_list()
SU

[[31, 36],
 [12, 34, 46],
 [28],
 [25],
 [44],
 [45],
 [23, 57, 58],
 [32, 39],
 [13, 30, 53],
 [9],
 [1, 20],
 [29, 47],
 [8, 56],
 [14, 42, 55],
 [6, 35],
 [15, 16, 24],
 [48],
 [2, 7, 11, 22],
 [21],
 [38, 40, 41],
 [43, 49],
 [0, 4, 18, 33, 52],
 [37],
 [5, 10, 26, 51],
 [17, 19, 27, 50, 59],
 [3, 54]]

In [ ]:
SEQ = df_serveis[['user','Type','Id']].groupby(by=['user','Type']).agg(list)['Id'].to_list()
SEQ

[[31],
 [36],
 [46],
 [12, 34],
 [28],
 [25],
 [44],
 [45],
 [57],
 [23],
 [58],
 [32],
 [39],
 [30, 53],
 [13],
 [9],
 [1],
 [20],
 [29, 47],
 [8],
 [56],
 [14, 42],
 [55],
 [35],
 [6],
 [15],
 [16, 24],
 [48],
 [2, 22],
 [7],
 [11],
 [21],
 [38],
 [41],
 [40],
 [43, 49],
 [52],
 [4, 18],
 [0],
 [33],
 [37],
 [5],
 [10, 51],
 [26],
 [27],
 [17, 59],
 [50],
 [19],
 [3],
 [54]]

In [ ]:
def sim_score(agent,user,service,non_valid=-1000):
        sim = 0
        if service.Type in agent.Qualifications :
            sim -= user.Age - agent.Age
            if agent.Gender == user.Gender:
                sim += 50
            num_common_lang = len(set(user.Languages) & set(agent.Languages))
            if num_common_lang == 1:
                sim += 100
            if agent.Race == user.Race:
                sim += 25
            sim -= int(distance(agent.Location, user.Location).km)
        else:
             sim = non_valid
        return sim

In [ ]:
def compute_quantiles(r,q,non_valid=-1000):
    for (x,y), value in np.ndenumerate(r):
        pass
        if value>=q[2]:
            r[x,y]=4
        elif value>=q[1]:
            r[x,y]=3
        elif value>=q[0]:
            r[x,y]=2
        elif value > -1000:
            r[x,y]=1
        else:
            r[x,y]=0
    return r

In [ ]:
r = np.ones((A,S))
for a in df_agents.iterrows():
    a=a[1]
    for s in df_serveis.iterrows():
        s=s[1]
        r[a.Id,s.Id] = sim_score(a,df_usuaris.iloc[s.user],s)

r = compute_quantiles(r,np.quantile(r.flatten()[r.flatten()>-1000],[0.25,0.50,0.75]))
np.unique(r, return_counts=True)

(array([0., 1., 2., 3., 4.]), array([841,  88,  91,  90,  90]))

In [ ]:
with open('instance.txt', 'w') as f:
    f.write('#U\n')
    f.write(str(U)+'\n')
    f.write('#S'+'\n')
    f.write(str(S)+'\n')
    f.write('#A\n')
    f.write(str(A)+'\n')
    f.write('#TS\n')
    f.write(str(TS)+'\n')
    f.write('#SU\n')
    for e in SU:
        f.write(str(e).replace('[','').replace(']','').replace(',','')+'\n')
    f.write('#SEQ\n')
    for e in SEQ:
        f.write(str(e).replace('[','').replace(']','').replace(',','')+'\n')
    f.write('#TSA(i)\n')
    for e in df_agents['TSA'].to_list():
        f.write(str(e).replace('[','').replace(']','').replace(',','')+'\n')
    f.write('#TSS(i)\n')
    for e in df_serveis['TimeSlot'].to_list():
        f.write(str(e).replace('[','').replace(']','').replace(',','')+'\n')
    f.write('#r(i,j)\n')
    for e in r.tolist():
        f.write(str(e).replace('[','').replace(']','').replace(',','').replace('.0','')+'\n')
    f.write('#P\n-1\n#HN(i)\n')
    for e in df_agents['TSA'].to_list():
        if sum(e)<=35:
            f.write(str(sum(e))+'\n')
        else:
            f.write('35\n')
    f.write('#HE(i)\n')
    for e in df_agents['TSA'].to_list():
        if sum(e)<=35:
            f.write('0\n')
        else:
            f.write(str(sum(e)-35)+'\n')